name: Build docker image for identity service

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14
      uses: actions/setup-node@master
      with:
        version: '14'
    - name: docker build
      run: docker build . --tag dokku/nws-identity -f Dockerfile.identity