name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 14
      uses: actions/setup-node@master
      with:
        version: '14'
    - name: npm install and test
      run: |
        npm install
        npm test
      shell: bash